repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
    -   id: black
-   repo: https://github.com/python-poetry/poetry
    rev: '1.7.0'
    hooks:
    -   id: poetry-check
        args: ["--lock"]
    # TODO: still need a `poetry update` check, `poetry lock` and `poetry check` don't check it.
    -   id: poetry-lock
    -   id: poetry-install
-   repo: https://github.com/aerickson/poetry
    rev: '539d1b0'  # add version here
    hooks:
    -   id: poetry-update
